// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMRHrQMZCeQQOcCyOeuVzJxvdRO14nMn4',
    appId: '1:764916743855:web:792ae7d5e1830750df1e5a',
    messagingSenderId: '764916743855',
    projectId: 'foodiezzzz',
    authDomain: 'foodiezzzz.firebaseapp.com',
    storageBucket: 'foodiezzzz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZmQhDyNgDzilhPijuAR4l32PFPSykgGU',
    appId: '1:764916743855:android:a4692f211a3ee934df1e5a',
    messagingSenderId: '764916743855',
    projectId: 'foodiezzzz',
    storageBucket: 'foodiezzzz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmQsGmoJaDA8OH2LvFVTKSToq-R0UKWx4',
    appId: '1:764916743855:ios:aa9d3af3b2f91e01df1e5a',
    messagingSenderId: '764916743855',
    projectId: 'foodiezzzz',
    storageBucket: 'foodiezzzz.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmQsGmoJaDA8OH2LvFVTKSToq-R0UKWx4',
    appId: '1:764916743855:ios:aa9d3af3b2f91e01df1e5a',
    messagingSenderId: '764916743855',
    projectId: 'foodiezzzz',
    storageBucket: 'foodiezzzz.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMRHrQMZCeQQOcCyOeuVzJxvdRO14nMn4',
    appId: '1:764916743855:web:38bba77f31651e98df1e5a',
    messagingSenderId: '764916743855',
    projectId: 'foodiezzzz',
    authDomain: 'foodiezzzz.firebaseapp.com',
    storageBucket: 'foodiezzzz.appspot.com',
  );
}
